require("barbar").setup({
    animation = true,
    clickable = true,
    exclude_ft = { "javascript" },
    exclude_name = { "package.json" },
    focus_on_close = "left",
    highlight_inactive_file_icons = false,
    highlight_visible = true,
    icons = {
        buffer_index = false,
        buffer_number = false,
        button = "",
        -- diagnostics = {
        --     [vim.diagnostic.severity.error] = { enabled = true, icon = "ﬀ" },
        --     [vim.diagnostic.severity.warn] = { enabled = false },
        --     [vim.diagnostic.severity.info] = { enabled = false },
        --     [vim.diagnostic.severity.hint] = { enabled = true },
        -- },
        diagnostics = {
            [1] = { enabled = true, icon = "ﬀ" },
            [2] = { enabled = false },
            [3] = { enabled = false },
            [4] = { enabled = true },
        },
        gitsigns = {
            added = { enabled = true, icon = "+" },
            changed = { enabled = true, icon = "~" },
            deleted = { enabled = true, icon = "-" },
        },
        filetype = {
            custom_colors = false,
            enabled = true,
        },
        separator = { left = "▎", right = "" },
        separator_at_end = true,
        modified = { button = "●" },
        pinned = { button = "", filename = true },
        preset = "default",
        alternate = { filetype = { enabled = false } },
        current = { buffer_index = false },
        inactive = { button = "×" },
        visible = { modified = { buffer_number = false } },
    },
    insert_at_end = true,
    maximum_padding = 1,
    minimum_padding = 1,
    maximum_length = 30,
    minimum_length = 0,
    semantic_letters = true,
    sidebar_filetypes = {
        nvimtree = true,
        undotree = { text = "undotree" },
        ["neo-tree"] = { event = "bufwipeout" },
        outline = { event = "bufwinleave", text = "symbols-outline" },
    },
    letters = "asdfjkl;ghnmxcvbziowerutyqpasdfjklghnmxcvbziowerutyqp",
    no_name_title = nil,
    scope = "tabpage",
    auto_hide = true,
})
